### ISSUE TITLE
Can't build ('make') lib on macOS Sierra v 10.12.6

### ISSUE THREAD

**Issue by volroman** [SeadexGmbH/yasmine#29] opened 2017-12-23 12:28 UTC
```
clang -v
Apple LLVM version 8.0.0 (clang-800.0.42.1)
Target: x86_64-apple-darwin16.7.0
Thread model: posix
```

```[ 68%] Building CXX object yasmine_model/CMakeFiles/libyasmine_model.dir/source/json_reader.cpp.o
/Users/alualu/Downloads/yasmine/yasmine_model/source/json_reader.cpp:558:8: error: no viable conversion from returned value of type 'SX_UNIQUE_PTR<model::transition_model_impl>'
      to function return type 'SX_UNIQUE_PTR<sxy::model::transition_model>'
        return( transition );
              ^~~~~~~~~~~~~~
```

**Comment by SeadexWP** [comment] 2017-12-23 13:00
Thank you for reporting the problem. We're gonna look into it.
From the error message I'd guess that there's an include missing (of transition_model_impl?!).
This should only affect the model library. It should be possible to build the core library (libyasmine).

**Comment by volroman** [comment] 2017-12-26 09:25
Thank you for looking into it! If you need any additional information, just let me know.

It looks like "transition_model_impl" is there and added to CMakeList. I'm performing very standard action order: Checkout, cmake, sudo make (with no custom parameters). No modifications, everything is "out of the box".

**Comment by SeadexWP** [comment] 2017-12-26 10:14
We'll be back @ work on Jan 8th. Then we'll have a look at it and fix it.
I took a short look at the code now and cannot see anything suspicious. The forward declarations look good the includes seem to be there. I guess else MSVC, gcc, and our clang version should have a problem, too...
We're gonna have to go with llvm 8.0.0 and see.

Maybe something is up with the namespace resolution:
> SX_UNIQUE_PTR<model::transition_model_impl>'
model without sxy
> 'SX_UNIQUE_PTR<sxy::model::transition_model>'
model with sxy

> It looks like "transition_model_impl" is there and added to CMakeList. 
> I'm performing very standard
> action order: Checkout, cmake, sudo make (with no custom parameters). No modifications, everything
> is "out of the box".
Yeah, I am very sure it has nothing to do with what you do or how your workflow looks.
Either the code is not clean (aka standard conforming) or llvm 8.0.0 has a quirk.

**Comment by SeadexTM** [comment] 2018-01-11 16:05
Hi,
We tried to reproduce the bug but no success.
We build yasmine using clang 3.9.0 (that is 8.0.0 (clang-800.0.42.1)) and clang 5.0.1 and we did not have that error.

**Comment by SeadexWP** [comment] 2018-02-07 05:04
We cannot reproduce the problem. 
As there is no further feedback, we'll close the issue.
If there is more info about the problem or a suggested fix, we can reopen this one.

**Closed by SeadexWP** 2018-02-07 05:04 UTC
